# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows/actions/deploy-eks
      - /.github/workflows/actions/test-eks
    schedule:
      interval: weekly

  # Maintain dependencies for Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  # Maintain dependencies for Docker
  - package-ecosystem: docker
    directories:
      - /dockerfiles/agents
      - /dockerfiles/app
      - /dockerfiles/endorser
      - /dockerfiles/tests
      - /dockerfiles/trustregistry
      - /dockerfiles/waypoint
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /dockerfiles/agents
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /dockerfiles/app
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /dockerfiles/endorser
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /dockerfiles/tests
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /dockerfiles/trustregistry
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /dockerfiles/waypoint
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /scripts/k6
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /scripts/k6
    schedule:
      interval: daily
